# NUMPY MODULE

NumPy is a powerful Python library for numerical and scientific computing. It provides support for multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays efficiently. Let's go over some of the key methods and features of NumPy with examples:

In [2]:
import numpy as np
# numpy module is generally used as "np"

**Advantages of NumPy:**

* **Performance:** NumPy operations are implemented in C and optimized for performance. This makes NumPy significantly faster than using Python's built-in data structures for numerical computations.<br>
* **Multidimensional Arrays:** NumPy provides efficient multi-dimensional arrays (ndarrays) that allow you to work with data of higher dimensions (such as matrices and tensors) more easily.<br>

* **Memory Efficiency:** NumPy arrays are more memory-efficient than Python lists, mainly because they store elements of the same data type. This also results in better cache utilization and overall faster computations.<br>

* **Vectorization:** NumPy encourages vectorized operations, where you can perform operations on entire arrays at once, eliminating the need for explicit looping. This simplifies code and improves performance.
cikit-learn.

## 1) Creating a Basic Array

To create a NumPy array, you can use the function np.array().

In [4]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [46]:
my_list = [1,2,3,4]
arr = np.array(my_list)
print(arr)
print()
my_list = [[1,2,3,4],[5,6,7,8]]
arr = np.array(my_list)
print(arr)


[1 2 3 4]

[[1 2 3 4]
 [5 6 7 8]]


In [51]:
# 2D arrays
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# 3D arrays 
np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [53]:
# Get Dimension
a =np.array([[1,2,3],[4,5,6]])
a.ndim

2

In [55]:
# Get Shape
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[5,6,7]])
print("a-->",a.shape,"\n", "b-->",b.shape)

a--> (2, 3) 
 b--> (2, 3)


**Arrays Filled with zeros, ones and other nums**

In [11]:
# Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:
np.zeros(2)

array([0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
# Or an array filled with 1’s:
np.ones(2)

array([1., 1.])

In [29]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [31]:
a = np.array([[1,2,3],[4,5,6]]) 
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [19]:
# Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. 
# The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!
np.empty(2) 

array([1., 1.])

In [20]:
# You can create an array with a range of elements:
np.arange(4)

array([0, 1, 2, 3])

In [28]:
# And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.
np.arange(2, 9, 2,)

array([2, 4, 6, 8])

In [30]:
np.arange(2, 9, 2).reshape(2,2)

array([[2, 4],
       [6, 8]])

In [31]:
# You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Specifying your data type**

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the **dtype** keyword.

In [32]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

**What does int8, int32, int64 mean?**
These terms refer to different data types for representing integers with varying ranges of values. The numbers in these terms represent the number of bits used to store each integer, which in turn determines the range of values that can be represented using that data type. For example: 
* int8 (8-bit integer):<br>
* 
Uses 8 bits (1 byte) to store each intege<br>
* .
Range: From -128 to 127 (inclusiv

The more bit, the more possible data to storage, also the more memory usage.e).

In [38]:
# Make sure that you use the right dtype for your data
np.array([127,12,0,-12,-128, -129, 128], dtype= np.int8)

C:\Users\Mehmet Emin\AppData\Local\Temp\ipykernel_14384\1788730000.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127,12,0,-12,-128, -129, 128], dtype= np.int8)
C:\Users\Mehmet Emin\AppData\Local\Temp\ipykernel_14384\1788730000.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127,12,0,-12,-128, -129, 128], dtype= np.int8)


array([ 127,   12,    0,  -12, -128,  127, -128], dtype=int8)

In [39]:
np.array([127,12,0,-12,-128, -129, 128], dtype= np.int32)

array([ 127,   12,    0,  -12, -128, -129,  128])

 **Using Multiple Datatype in Arrays**<br>
 It is possible to use multiple datatypes in arrays with some ways, but generally arrays use one type of data since it is more efficient.
 Use .dtype method to see what datatype an array uses

In [42]:
# Structured Arrays

data = np.array([(1, 2.0, 'Hello'), (2, 3.5, 'World')], dtype=[('x', int), ('y', float), ('z', 'S10')])
print(data)
print(data.dtype)

[(1, 2. , b'Hello') (2, 3.5, b'World')]
[('x', '<i4'), ('y', '<f8'), ('z', 'S10')]


In [43]:
# Object Arrays
data = np.array([1, 'Hello', 3.14, [1, 2, 3]], dtype=object)
print(data)
print(data.dtype)

[1 'Hello' 3.14 list([1, 2, 3])]
object


**2D array creation functions**

The 2D array creation functions e.g. **numpy.eye**, **np.identity**, **numpy.diag**, and **numpy.vander** define properties of special matrices represented as 2D arrays.

* np.eye(n, m) defines a 2D identity matrix. The elements where i=j (row index and column index are equal) are 1 and the rest are 0, as such:
* np.identity(n) also gives the same result, but np.eye is more flexible.

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
np.eye(3,5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements. The two array creation functions can be helpful while doing linear algebra, as such:

In [5]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [7]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

* vander(x, n) defines a Vandermonde matrix as a 2D NumPy array. Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, x where the highest polynomial order is n-1. This array creation routine is helpful in generating linear least squares models, as such:

In [8]:
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [9]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [10]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

**Random Array Creation**

* np.random.rand(shape) - Generating Random Numbers:<br>
This function generates random numbers between 0 and 1 and returns a NumPy array with the specified shape.
* np.random.randn(shape) - Generating Random Numbers:<br>
This function generates random numbers between -1 and 1 and returns a NumPy array with the specified shape in Gausian Distribution.

In [12]:
np.random.rand(3, 4)

array([[0.67385044, 0.78605789, 0.33857567, 0.5990439 ],
       [0.64897366, 0.38778215, 0.55968051, 0.211053  ],
       [0.37132441, 0.55158923, 0.75097415, 0.02688612]])

In [19]:
np.random.randn(3,4)

array([[-0.93656865, -0.947621  ,  1.62435384, -1.20960401],
       [ 0.56801077,  0.19870332, -0.2337022 , -0.21184441],
       [ 0.19264891,  0.69436724,  0.35338066, -0.87407165]])

* np.random.randint(low, high, size) - Generating Random Integers in a Range:<br>
This function generates random integers within a specified range (low inclusive, high exclusive).

In [15]:
np.random.randint(1, 10, size=5)

array([1, 2, 6, 8, 5])

In [20]:
np.random.randint(1, 10, size=(2,3))

array([[4, 9, 1],
       [9, 1, 7]])

* np.random.normal(mean, std, size) - Generating Random Numbers from Normal Distribution:<br>
This function generates random numbers following a normal distribution with the specified mean and standard deviation.

In [18]:
np.random.normal(0, 1, size=10)

array([ 0.46517874, -1.17532182,  0.34156089, -0.42629541,  0.79734876,
        0.07225738,  1.01425164,  0.11053314,  2.14015886,  0.07784012])

**Itemsize and Size**

* itemsize:<br>
The itemsize attribute of a NumPy array represents the number of bytes used to store each individual element (item) in the array. It gives you the memory size of a single element in the array. Use .nbytes to get total size.

In [21]:
int_array = np.array([1, 2, 3, 4], dtype=np.int32)
int_array.itemsize  # Returns 4

4

In [25]:
int_array.nbytes  #items*itemsize

16

* size:<br>
The size attribute of a NumPy array gives the total number of elements in the array. It indicates the count of elements, regardless of their individual sizes.

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.size  # Returns 6 (two rows with three elements each)

6

## 2) Indexing and Slicing

**Single element indexing**<br>
Single element indexing works exactly like that for other standard Python sequences. It is 0-based, and accepts negative indices for indexing from the end of the array.

In [35]:
x = np.arange(10)
print(x)
x[2]

[0 1 2 3 4 5 6 7 8 9]


2

In [33]:
x[-2]

8

In [36]:
x.shape = (2, 5)  # now x is 2-dimensional
print(x)
x[1, 3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


8

Note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. For example:

In [37]:
x[0]

array([0, 1, 2, 3, 4])

note that x[0, 2] == x[0][2] though the second case is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.

In [38]:
x[0][2]

2

**Slicing and Striding**

Basic slicing extends Python’s basic concept of slicing to N dimensions. Basic slicing occurs when obj is a slice object (constructed by start:stop:step notation inside of brackets), an integer, or a tuple of slice objects and integers.<br>
The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step (k is not 0
).

In [39]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [40]:
# Negative i and j are interpreted as n + i and n + j where n is the number of elements in the corresponding dimension. 
# Negative k makes stepping go towards smaller indices. From the above example:
x[-2:10]

array([8, 9])

In [41]:
x[-3:3:-1]

array([7, 6, 5, 4])

If the number of objects in the selection tuple is less than N, then : is assumed for any subsequent dimensions. For example:

In [42]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x)
x.shape

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


(2, 3, 1)

In [43]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [44]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(matrix[0, 1])  # Access element at row 0, column 1 (2)
print(matrix[1:, :2])  # Extract subarray from rows 1 and 2, and columns 0 and 1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[4 5]
 [7 8]]


In [46]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
# Get a specific element [r, c]
print(a[1, 5])

# Get a specific row 
print(a[0, :])

# Get a specific column
print(a[:, 2])

# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:-1:2])


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]


In [85]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# replace 
b[:,1,:] = [[9,9,9],[8,8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [48]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

**Choosing Specific Elements**

* np.take() function is used to retrieve specific elements from an array based on their indices. It can be especially useful when you want to extract elements from an array using a list of indices.

In [78]:
arr = np.array([10, 20, 30, 40, 50])
indices = [1, 3]

selected_elements = np.take(arr, indices)

print("Selected Elements:")
print(selected_elements)


Selected Elements:
[20 40]


In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = [0, 2]
col_indices = [1, 2]

selected_elements = np.take(arr, [row_indices, col_indices])

print("Selected Elements:")
print(selected_elements)

Selected Elements:
[[1 3]
 [2 3]]


* Fancy Indexing: Turns whole matrix into a list and chooses wanted elements

In [81]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
indices = [0, 1, 4, 9, 11, 13]
selected_values = arr.flat[indices]
print(selected_values)

[ 1  2  5 10 12 14]


* Slicing Method

In [83]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
selected_values = arr[[0, 0, 0, 1, 1, 1], [0, 1, 4, 2, 4, -1]]
print(selected_values)

[ 1  2  5 10 12 14]


NOTE: **numpy.indices** will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension:

In [84]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

## 3) Replicating, Joining, or Mutating Existing Arrays

#### **Replicating Arrays:** copy(), np.repeat(), np.tile()

* Use copy() when you want to change over an array and do not want to this change affect the original one.

In [87]:
original_arr = np.array([1, 2, 3, 4, 5])

# Creating a new variable referencing the same array (not a copy)
new_arr_ref = original_arr

# Creating an independent copy of the array using copy()
new_arr_copy = original_arr.copy()

# Modifying the new_arr_ref will also modify the original_arr
new_arr_ref[0] = 100

print(original_arr)
print(new_arr_ref)
print(new_arr_copy)

[100   2   3   4   5]
[100   2   3   4   5]
[1 2 3 4 5]


* np.repeat()

In [89]:
arr = np.array([1, 2, 3])

# Repeating each element three times
repeated_arr = np.repeat(arr, 3)
print(repeated_arr)

[1 1 1 2 2 2 3 3 3]


In [91]:
arr = np.array([[1, 2], [3, 4]])

repeated_arr = np.repeat(arr, 2, axis=0)
print(repeated_arr)

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [92]:
arr = np.array([[1, 2], [3, 4]])

repeated_arr = np.repeat(arr, 2, axis=1)
print(repeated_arr)

[[1 1 2 2]
 [3 3 4 4]]


* np.tile()

In [95]:
arr = np.array([1, 2, 3])
# Creating a 2x3 array by tiling the original array
tiled_arr = np.tile(arr, 2)
print(tiled_arr)

[1 2 3 1 2 3]


In [97]:
arr = np.array([1, 2, 3])
# Creating a 2x3 array by tiling the original array
tiled_arr = np.tile(arr, (2,1))
print(tiled_arr)

[[1 2 3]
 [1 2 3]]


In [98]:
arr = np.array([[1, 2], [3, 4]])

tiled_arr = np.tile(arr, (2, 3))
print(tiled_arr)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


#### **Joining Arrays:** np.concatenate(),  np.vstack(),  np.hstack()


In [101]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6],[7,8]])

# Concatenating arrays horizontally (column-wise)
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
concatenated_arr2 = np.concatenate((arr1, arr2), axis=1)
print("Concatenated Array:")
print(concatenated_arr)
print(concatenated_arr2)

Concatenated Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [102]:
# Stacking arrays vertically (row-wise)
stacked_arr = np.vstack((arr1, arr2))
print("Stacked Array:")
print(stacked_arr)

Stacked Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [103]:
# Stacking arrays horizontally (column-wise)
stacked_arr = np.hstack((arr1, arr2))
print("Stacked Array:")
print(stacked_arr)

Stacked Array:
[[1 2 5 6]
 [3 4 7 8]]


#### **Mutating Arrays**

In [104]:
arr = np.array([1, 2, 3, 4, 5])

# Changing an element at a specific index
arr[2] = 7
print("Modified Array:")
print(arr)

# Modifying a slice of the array
arr[1:4] = 0
print("Modified Slice:")
print(arr)


Modified Array:
[1 2 7 4 5]
Modified Slice:
[1 0 0 0 5]


In [105]:
# Broadcasting
arr = np.array([[1, 2], [3, 4]])

# Broadcasting a scalar value to the entire array
arr += 5
print("Broadcasted Array:")
print(arr)


Broadcasted Array:
[[6 7]
 [8 9]]


#### **Reshaping Arrays**

In [108]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping array to a different shape
reshaped_arr = np.reshape(arr, (3, 2))
print("Reshaped Array:")
print(reshaped_arr)

# Flattening the array to a 1D array
flattened_arr = np.ravel(arr)
print("Flattened Array:")
print(flattened_arr)

Reshaped Array:
[[1 2]
 [3 4]
 [5 6]]
Flattened Array:
[1 2 3 4 5 6]


## 4) Mathematics

**Basic Arithmetic Operations:** <br>
NumPy supports basic arithmetic operations such as addition, subtraction, multiplication, and division on arrays. These operations are element-wise.

In [51]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,5],[6,7]])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr2 / arr1

print(addition)       # [5 7 9]
print(subtraction)    # [-3 -3 -3]
print(multiplication) # [4 10 18]
print(division)       # [4.  2.5 2.]


[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]
[[ 4 10]
 [18 28]]
[[4.   2.5 ]
 [2.   1.75]]


**Universal Functions (ufuncs):** <br>
NumPy's universal functions (ufuncs) are functions that operate element-wise on arrays, performing fast mathematical computations.

In [54]:
arr = np.array([1, 2, 3, 4])

squared = np.square(arr)   # Element-wise square
sqrt = np.sqrt(arr)         # Element-wise square root
exp = np.exp(arr)           # Element-wise exponential
log = np.log(arr)           # Element-wise natural logarithm
print(squared, sqrt, exp, log, sep="\n")

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


**Aggregate Functions:** <br>
NumPy provides functions to compute aggregate values across an array, like sum, mean, median, maximum, and minimum.

In [56]:
arr = np.array([1, 2, 3, 4, 5])

sum_arr = np.sum(arr)
mean_arr = np.mean(arr)
median_arr = np.median(arr)
max_arr = np.max(arr)
min_arr = np.min(arr)
print(sum_arr, mean_arr, median_arr,max_arr, min_arr, sep="\n" )

15
3.0
3.0
5
1


In [58]:
arr = np.array([[6,2,7], [4,3,6]])
np.median(arr) # firstly it sorts number and then finds median [2,3,4,6,6,7]

5.0

**Axis Parameter**<br>
The axis parameter allows you to control the direction of operations, such as summation, mean calculation, and more, along specific axes.
* axis=0 --> operation among **columns**
* axis=1 --> operation among **rows**

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum along axis 0 (sum of columns)
sum_along_axis_0 = np.sum(arr, axis=0)
print(sum_along_axis_0)  # Output: [5 7 9]

# Sum along axis 1 (sum of rows)
sum_along_axis_1 = np.sum(arr, axis=1)
print(sum_along_axis_1)  # Output: [ 6 15]


[5 7 9]
[ 6 15]


In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Maximum along axis 0 (maximum value in each column)
max_along_axis_0 = np.max(arr, axis=0)
print(max_along_axis_0)  # Output: [4 5 6]

# Minimum along axis 1 (minimum value in each row)
min_along_axis_1 = np.min(arr, axis=1)
print(min_along_axis_1)  # Output: [1 4]

[4 5 6]
[1 4]


## 5) Linear Algebra

**Matrix Multiplication:** <br>
There are several methods for matrix multipication: dot(), matmul(). Both of them can be used for 2D matrices, but use dot() for dot product of vectors.

In [62]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)  # or equivalently: A @ B
print(result)


[[19 22]
 [43 50]]


In [63]:
A@B

array([[19, 22],
       [43, 50]])

In [64]:
np.matmul(A,B)

array([[19, 22],
       [43, 50]])

**Matrix Inversion**

In [65]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)

print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


**Determinant**

In [66]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)

print(det_A)

-2.0000000000000004


**Transpose**

In [77]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# transposed_arr = np.transpose(arr)
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

**Eigenvalues and Eigenvectors**


In [67]:
A = np.array([[1, -2], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [2.+1.73205081j 2.-1.73205081j]
Eigenvectors: [[-0.70710678+0.j         -0.70710678-0.j        ]
 [ 0.35355339+0.61237244j  0.35355339-0.61237244j]]


**Solving Linear Equations**

In [68]:
A = np.array([[2, 1], [1, 1]])
b = np.array([3, 2])

x = np.linalg.solve(A, b)

print(x)

[1. 1.]


**Singular Value Decomposition (SVD)**

In [69]:
A = np.array([[1, 2, 3], [4, 5, 6]])
U, S, V = np.linalg.svd(A)

print("U:", U)
print("S:", S)
print("V:", V)

U: [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
S: [9.508032   0.77286964]
V: [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


**QR Decomposition**

In [70]:
A = np.array([[1, 2], [3, 4]])
Q, R = np.linalg.qr(A)

print("Q:", Q)
print("R:", R)

Q: [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R: [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


**Cholesky Decomposition**

In [71]:
A = np.array([[4, 2], [2, 5]])
L = np.linalg.cholesky(A)

print("L (Cholesky Factor):", L)

L (Cholesky Factor): [[2. 0.]
 [1. 2.]]


**Matrix Rank**

In [72]:
A = np.array([[1, 2], [3, 4]])
rank_A = np.linalg.matrix_rank(A)

print("Matrix Rank:", rank_A)

Matrix Rank: 2


**Norms**

In [73]:
A = np.array([[1, 2], [3, 4]])

# Frobenius norm
norm_frobenius = np.linalg.norm(A, 'fro')
print("Frobenius Norm:", norm_frobenius)

# L2 norm (default)
norm_l2 = np.linalg.norm(A)
print("L2 Norm:", norm_l2)

# L1 norm
norm_l1 = np.linalg.norm(A, ord=1)
print("L1 Norm:", norm_l1)

Frobenius Norm: 5.477225575051661
L2 Norm: 5.477225575051661
L1 Norm: 6.0


**Pseudo-Inverse (Moore-Penrose Inverse)**

In [76]:
A = np.array([[1, 2], [3, 4]])
A_pseudo_inv = np.linalg.pinv(A)

print("Pseudo-Inverse:", A_pseudo_inv)

Pseudo-Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
